### ISSUE TITLE
Add product -> New publisher created with blank data

### ISSUE THREAD

**Issue by antonym8** [antonym8/Selvi-Books#14]
New publisher created without enter any name and it's showing as 'null' in the publisher field

![Screenshot (95)](https://github.com/antonym8/Selvi-Books/assets/142376069/1b509714-f34b-45c7-b1b9-7afed9447f64)
![Screenshot (96)](https://github.com/antonym8/Selvi-Books/assets/142376069/d5339788-ebee-44df-988f-fda61b6e1094)

**Comment by gurum8** [comment]
Fixed
