### ISSUE TITLE
Purchase management / Vendors -> Search not working properly

### ISSUE THREAD

**Issue by antonym8** [antonym8/Selvi-Books#25]
![Screenshot (112)](https://github.com/antonym8/Selvi-Books/assets/142376069/4c17bc57-eefb-497f-9947-e5161a0f40a5)
![Screenshot (113)](https://github.com/antonym8/Selvi-Books/assets/142376069/01361d39-c598-44fb-bdea-e76b7167ffe2)

**Comment by gurum8** [comment]
Fixed
